name: solarshare
services:
- name: web
  source_dir: /
  github:
    repo: parthvast13/SolarShare
    branch: main
  run_command: python3 main.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /